test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  database: railspg_test
  username: <%=ENV['PGUSER']%>
  password: <%=ENV['PGPASSWORD']%>
  host:     localhost
  port:     <%=ENV['PGPORT']%>

development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  database: railspg_development
  username: <%=ENV['PGUSER']%>
  password: <%=ENV['PGPASSWORD']%>
  host:     localhost
  port:     <%=ENV['PGPORT']%>

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
